openapi: 3.0.0
info:
  title: REST-API for Weather-Service
  description: Use this Service to gather weather information for a given city.
  

servers:
  - url: http://localhost:5000/weather_service_api
    description: Development server (using locally)


paths:
  "/current-weather":
    post:
      summary: Get the current weather information for your city .
      description: Return the current weather information like temperature, cloudiness and more for your city or coordinates as well the corresponding widget.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                city:         # <!--- form field name
                  type: string
                unit:    # <!--- form field name
                  type: string
                  enum: ["metric", "imperial"]
              required:
                - city
                - unit
      tags:
        - Weather
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  city_name:
                    type: string
                    description: The cities name of the weather information.
                  weather:
                    type: object
                    properties:
                      main:
                        type: string
                        description: Group of weather parameters (Rain, Snow, Extreme etc.)
                      description:
                        type: string
                        description: Weather condition within the group.
                      icon:
                        type: string
                        description: Icon ID.
                      cloudiness:
                        type: number
                        description: The cloudiness in %.
                      wind:
                        type: object
                        properties:
                          speed:
                            type: number
                            description: Wind speed.
                          deg:
                            type: number
                            description: Wind direction, degrees.
                        required:
                          - speed
                          - deg
                      temp:
                        type: object
                        properties:
                          current:
                            type: number
                            description: Current temperature in Celsius.
                          feels_like:
                            type: number
                            description: This temperature parameter accounts for the human perception of weather.
                          min:
                            type: number
                            description: Minimum temperature in the moment.
                          max:
                            type: number
                            description: Maximum temperature at the moment.
                        required:
                          - current
                          - feels_like
                          - min
                          - max
                    required:
                      - cloudiness
                      - main
                      - description
                      - icon
                  time:
                    type: object
                    properties:
                      current:
                        type: integer
                        description: Time of data calculation, unix, UTC.
                      timezone:
                        type: integer
                        description: Shifts in seconds from UTC.
                      sunrise:
                        type: integer
                        description: Sunrise time, unix, UTC.
                      sunset:
                        type: integer
                        description: Sunset time, unix, UTC.
                    required:
                      - current
                      - timezone
                      - sunrise
                      - sunset
                  widget:
                    type: string
                    description: html code for the current-weather widget.
                required:
                  - city_name
                  - weather
                  - time
                  - widget
                example:
                  city_name: Stuttgart
                  weather:
                    main: Clouds
                    description: scattered clouds
                    icon: 10d
                    cloudiness: 40
                    wind:
                      speed: 5.66
                      deg: 340
                    temp:
                      current: 8.59
                      feels_like: 3.83
                      min: 8
                      max: 8.89
                  time:
                    current: 1614358854
                    timezone: 3600
                    sunrise: 1614319871
                    sunset: 1614358891
                  # widget: '<div id=''openweathermap-widget-21''></div><script src=''//openweathermap.org/themes/openweathermap/assets/vendor/owm/js/d3.min.js''></script\>\<script\>window.myWidgetParam ? window.myWidgetParam : window.myWidgetParam = [];  window.myWidgetParam.push({id: 21,cityid: ''2825297'',appid: ''b6813f52b32285369417e4defa12c6db'',units: ''metric'',containerid: ''openweathermap-widget-21'',  });  (function() {var script = document.createElement(''script'');script.async = true;script.charset = ''utf-8'';script.src = ''//openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js'';var s = document.getElementsByTagName(''script'')[0];s.parentNode.insertBefore(script, s);  })();\</script\>'
        "400":
          description: `city` is required.
        "500":
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  info:
                    type: string
                    description: General information about error.
                  error:
                    type: object
                    properties:
                      code:
                        type: integer
                        description: Status code from third party api.
                      message:
                        type: string
                        description: Error message from third party api.
                      full_error:
                        type: string
                        description: Full error message from third party api.
                    required:
                      - code
                      - message
                      - full_error
                required:
                  - info
                  - error
                example:
                  info: Internal server error caused by third party api.
                  error:
                    code: 400
                    message: Bad Request
                    full_error: "400 Client Error: Bad Request for url: http://api.openweathermap.org/data/2.5/weather?q=&appid=b6813f52b32285369417e4defa12c6db&units=metric"
